### ISSUE TITLE
Consider making Currency something more flexible than enum

### ISSUE THREAD

**Issue by keilw** [openbankingnigeria/api#9]
The Currency is a simple enum right now with just 3 or 4 possible values. Consider making this more flexible, e.g. by using [JavaMoney-API](https://github.com/JavaMoney/jsr354-api)

Happy to help applying JavaMoney in this project, just give us a shout.

**Comment by damilolasodiq** [comment]
Hi,
You can create a PR for the issue. I would be happy to review and merge. I quite agree with you on the usage of money API rather than the enum.

**Comment by keilw** [comment]
I created a fork https://github.com/JavaMoney/openbankingng-api.
Are any of you familiar with the Lagos Java User Group? [JCP ](https://jcp.org/en/home/index) Chair Heather Van Cura was there last November: http://blackboxnigeria.com/2017/11/13/pictures-lagos-java-users-hang-heather-vancura-java-community-process/

**Comment by keilw** [comment]
I did, https://github.com/openbankingnigeria/api/pull/11

**Comment by damilolasodiq** [comment]
> I did, #11

Approved
